apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: site1
  namespace: default
spec:
  interval: 5m
  url: https://github.com/kangwarn/keswick.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site1
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: site1
  path: "./base
  prune: true
  timeout: 1m
