apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: base
  namespace: default
spec:
  interval: 5m
  url: https://github.com/kangwarn/keswick.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site1
  namespace: default
spec:
  interval: 10m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: base
  path: "./kustomize"
  prune: true
  timeout: 1m
  patches:
    - patch: |
        - op: replace
          path: /spec/className
          value: best-effort-xsmall
        - op: replace
          path: /spec/imageName
          value: 192.168.101.14/jammy-server-cloudimg-amd64.ova
      target:
        kind: VirtualMachine
        name: linux-vm
