apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: best-effort-ec-small
spec:
  controllerName: vmoperator.vmware.com/ecworker
  hardware:
    cpus: 2
    memory: 8Gi
    devices:
      dynamicDirectPathIODevices:
        - deviceID: 0x9a49
          vendorID: 0x8086
  configSpec:
    _typeName: VirtualMachineConfigSpec
    memoryReservationLockedToMax: true
    numCoresPerSocket: 2
#     extraConfig:
#       - _typeName: OptionValue
#         key: "pciPassthru.64bitMMIOSizeGB"
#         value: "64"
#       - _typeName: OptionValue
#         key: "pciPassthru.use64bitMMIO"
#         value: "true"
  policies:
    resources:
      requests:
        cpu: 2000m
        memory: 8Gi
      limits:
        cpu: 2000m
        memory: 8Gi
---
apiVersion: v1
kind: Namespace
metadata:
  name: ec-system
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ec-worker
  namespace: ec-system
spec:
  className: best-effort-ec-small
  imageName: ec-wrkr.ova
  powerState: poweredOff
  vmMetadata:
    transport: CloudInit
