apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site2-metrics-in-a-box
  namespace: default
spec:
  interval: 5m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: base
  path: "./metrics-in-a-box/kustomize"
  prune: true
  timeout: 1m
  patches:
    - patch: |
        - op: replace
          path: /spec/metrics-collection/metrics-sink/url
          value: "http://172.20.0.181:30777/api/v1/write"
      target:
        kind: HostConfiguration
        name: ecsmonitoring-metrics
        namespace: esx-system
