apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: base
  namespace: default
spec:
  interval: 5m
  url: https://github.com/kangwarn/keswick.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site2
  namespace: default
spec:
  interval: 10m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: base
  path: "./kustomize"
  prune: true
  timeout: 1m
  patches:
    - patch: |
        - op: replace
          path: /spec/imageName
          value: 172.20.0.200/jammy-server-cloudimg-amd64.ova
      target:
        kind: VirtualMachine
        name: linux-vm
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site2-intelgpu-nfd
  namespace: default
spec:
  interval: 10m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: base
  path: "./gpu/intel/nfd"
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site2-intelgpu-node-feature-rules
  namespace: default
spec:
  dependsOn:
    - name: site2-intelgpu-nfd
      namespace: default
  interval: 10m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: base
  path: "./gpu/intel/node-feature-rules"
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site2-intelgpu-operator
  namespace: default
spec:
  dependsOn:
    - name: site2-intelgpu-node-feature-rules
      namespace: default
  interval: 10m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: base
  path: "./gpu/intel/intel-gpu-operator"
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site2-intelgpu-test
  namespace: default
spec:
  dependsOn:
    - name: site2-intelgpu-operator
      namespace: default
  interval: 10m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: base
  path: "./gpu/intel/test"
  prune: true
  timeout: 1m
