apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: base
  namespace: default
spec:
  interval: 5m
  url: https://github.com/kangwarn/keswick.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site4
  namespace: default
spec:
  interval: 5m
  # targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: base
  path: "./kustomize"
  prune: true
  timeout: 1m
